#
# Module manifest for module 'PSWinOps'
#
# Generated by: Franck SALLET
#
# Generated on: 10/04/2026
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule           = 'PSWinOps.psm1'

    # Version number of this module.
    ModuleVersion        = '1.1.0'

    # Supported PSEditions
    # Core is supported on Windows only; the module-level guard in PSWinOps.psm1 blocks
    # non-Windows hosts. Exchange snapin (Add-PSSnapin) is Desktop-only but the function
    # gracefully falls back to Import-Module on Core (see Get-ExchangeServerHealth).
    CompatiblePSEditions = 'Desktop', 'Core'

    # ID used to uniquely identify this module
    GUID                 = 'b8f23fbd-069e-4d11-8e94-e4fc69d71aa5'

    # Author of this module
    Author               = 'Franck SALLET'

    # Company or vendor of this module
    CompanyName          = 'kfrlabs'

    # Copyright statement for this module
    Copyright            = '(c) Franck SALLET. All rights reserved.'

    # Description of the functionality provided by this module
    Description          = 'A collection of PowerShell utilities for Windows system administrators'

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion    = '5.1'

    # Name of the PowerShell host required by this module
    # PowerShellHostName = ''

    # Minimum version of the PowerShell host required by this module
    # PowerShellHostVersion = ''

    # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # DotNetFrameworkVersion = ''

    # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # ClrVersion = ''

    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''

    # Modules that must be imported into the global environment prior to importing this module
    # RequiredModules = @()
    # NOTE: Several public functions lazy-import optional modules (ActiveDirectory, Hyper-V,
    # FailoverClusters, DhcpServer, DnsServer, WebAdministration, IISAdministration,
    # FileServerResourceManager, ExchangeManagementShell, RemoteDesktop, UpdateServices,
    # ADFS, PrintManagement, DFSN). None are listed in RequiredModules so the module
    # remains loadable on hosts that only need a subset of its surface.
    # See the "Optional Dependencies" section in readme.md for the full install reference.

    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies = @()

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # Enum types must be defined here (not inside the module) so consumers can reference
    # [PSWinOpsHealthStatus]::Healthy in typed parameters and parse-time expressions.
    ScriptsToProcess     = @('PSWinOpsHealthStatus.ps1')

    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    FormatsToProcess     = 'PSWinOps.Format.ps1xml'

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    # NestedModules = @()

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport    = @(
        'Clear-Arp',
        'Clear-DiskCleanup',
        'Clear-WindowsUpdateCache',
        'Connect-RdpSession',
        'ConvertFrom-MisencodedString',
        'ConvertTo-Markdown',
        'Disable-ADUserAccount',
        'Disconnect-RdpSession',
        'Edit-HostsFile',
        'Enable-ADUserAccount',
        'Export-NetworkConfig',
        'Get-ADComputerDetail',
        'Get-ADComputerInventory',
        'Get-AdDomainControllerHealth',
        'Get-ADDomainInfo',
        'Get-ADFSHealth',
        'Get-ADGroupInventory',
        'Get-ADGroupMembership',
        'Get-ADLockedAccount',
        'Get-ADLockoutSource',
        'Get-ADNestedGroupMembership',
        'Get-ADPasswordStatus',
        'Get-ADPrivilegedAccount',
        'Get-ADReplicationStatus',
        'Get-ADSiteTopology',
        'Get-ADStaleAccount',
        'Get-ADStaleComputer',
        'Get-ADUserDetail',
        'Get-ADUserGroupInventory',
        'Get-ADUserInventory',
        'Get-ARPTable',
        'Get-AuditPolicy',
        'Get-CertificateAuthorityHealth',
        'Get-ClusterHealth',
        'Get-ComputerUptime',
        'Get-CrashDump',
        'Get-DfsNamespaceHealth',
        'Get-DfsReplicationHealth',
        'Get-DhcpServerHealth',
        'Get-DiskCleanupInfo',
        'Get-DiskErrorEvent',
        'Get-DiskSpace',
        'Get-DnsServerHealth',
        'Get-DriverInventory',
        'Get-EnvironmentVariable',
        'Get-ExchangeServerHealth',
        'Get-ExpiringCertificate',
        'Get-FileServerHealth',
        'Get-HyperVHostHealth',
        'Get-IISAppPoolHistory',
        'Get-IISCertificateBinding',
        'Get-IISCurrentRequest',
        'Get-IISFailedRequestTrace',
        'Get-IISHealth',
        'Get-IISParsedLog',
        'Get-IISWorkerProcess',
        'Get-InstalledSoftware',
        'Get-ListeningPort',
        'Get-LogonFailure',
        'Get-NetworkAdapter',
        'Get-NetworkCIDR',
        'Get-NetworkConnection',
        'Get-NetworkRoute',
        'Get-NetworkStatistic',
        'Get-NTPConfiguration',
        'Get-NTPPeer',
        'Get-NTPSyncStatus',
        'Get-PageFileConfiguration',
        'Get-PendingReboot',
        'Get-PrintServerHealth',
        'Get-ProcessByPort',
        'Get-ProcessCrashEvent',
        'Get-ProxyConfiguration',
        'Get-PublicIPAddress',
        'Get-RdpSession',
        'Get-RdpSessionHistory',
        'Get-RdpSessionLock',
        'Get-RDSHealth',
        'Get-RebootHistory',
        'Get-SchannelError',
        'Get-ScheduledTaskDetail',
        'Get-ScheduledTaskFailure',
        'Get-ServiceAccount',
        'Get-ServiceCrashEvent',
        'Get-ServiceHealth',
        'Get-ShadowCopy',
        'Get-ShadowCopyStorage',
        'Get-SSLCertificate',
        'Get-StartupProgram',
        'Get-SubnetInfo',
        'Get-SystemSummary',
        'Get-UnexpectedShutdown',
        'Get-WindowsUpdate',
        'Get-WindowsUpdateConfiguration',
        'Get-WindowsUpdateFailure',
        'Get-WindowsUpdateHistory',
        'Get-WSUSHealth',
        'Hide-WindowsUpdate',
        'Install-WindowsUpdate',
        'Invoke-ADSecurityAudit',
        'Measure-NetworkLatency',
        'New-NetworkRoute',
        'New-RandomPassword',
        'New-ShadowCopy',
        'Remove-NetworkRoute',
        'Remove-ProxyConfiguration',
        'Remove-RdpSession',
        'Remove-ShadowCopy',
        'Remove-StringDiacritic',
        'Remove-UserProfile',
        'Reset-ADUserPassword',
        'Reset-NetworkStack',
        'Reset-WindowsUpdateComponent',
        'Resolve-MACVendor',
        'Restore-ShadowCopyFile',
        'Save-WindowsUpdate',
        'Search-ADObject',
        'Set-EnvironmentVariable',
        'Set-IISBindingCertificate',
        'Set-NetworkRoute',
        'Set-NTPClient',
        'Set-PageFile',
        'Set-ProxyConfiguration',
        'Set-ShadowCopyStorage',
        'Show-NetworkStatisticMonitor',
        'Show-PingMonitor',
        'Show-SystemMonitor',
        'Show-WindowsUpdate',
        'Stop-ProcessTree',
        'Sync-NTPTime',
        'Test-DNSResolution',
        'Test-IISBindingCertificate',
        'Test-PortConnectivity',
        'Test-ProxyConnection',
        'Test-WinRM',
        'Trace-NetworkRoute',
        'Uninstall-WindowsUpdate',
        'Unlock-ADUserAccount',
        'Watch-IISLog'
    )

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport      = @()

    # Variables to export from this module
    # VariablesToExport = @()

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport      = @(
        'cfms',
        'cla',
        'cldc',
        'clwuc',
        'conrs',
        'ctm',
        'dconrs',
        'disaua',
        'ehf',
        'enaua',
        'expnc',
        'gacd',
        'gaci',
        'gadch',
        'gadi',
        'gagi',
        'gagm',
        'gah',
        'gala',
        'gals',
        'gangm',
        'gap',
        'gapa',
        'gaps',
        'gars',
        'gasa',
        'gasc',
        'gast',
        'gat',
        'gaud',
        'gaugi',
        'gaui',
        'gcah',
        'gcd',
        'gch',
        'gcu',
        'gdci',
        'gdee',
        'gdi',
        'gdnh',
        'gdrh',
        'gds',
        'gdsh',
        'gdshe',
        'gec',
        'gesh',
        'gev',
        'gfsh',
        'ghvhh',
        'giaph',
        'gicb',
        'gicr',
        'gifrt',
        'gih',
        'gipl',
        'gis',
        'giwp',
        'glf',
        'glp',
        'gna',
        'gnc',
        'gnci',
        'gnco',
        'gnp',
        'gnr',
        'gns',
        'gnss',
        'gpbp',
        'gpc',
        'gpce',
        'gpfc',
        'gpia',
        'gpr',
        'gpsh',
        'grh',
        'grhi',
        'grs',
        'grsh',
        'grsl',
        'gsa',
        'gsc',
        'gsce',
        'gsco',
        'gscs',
        'gse',
        'gsh',
        'gsi',
        'gsp',
        'gss',
        'gstd',
        'gstf',
        'gus',
        'gwh',
        'gwu',
        'gwuc',
        'gwuf',
        'gwuh',
        'hwu',
        'iasa',
        'inswu',
        'mnl',
        'nnr',
        'nrp',
        'nsc',
        'restscf',
        'rnr',
        'rpc',
        'rrs',
        'rsc',
        'rsd',
        'rslvmv',
        'rstaup',
        'rstns',
        'rstwuc',
        'rup',
        'seao',
        'sev',
        'shnsm',
        'shpm',
        'shsm',
        'shwu',
        'sibc',
        'snc',
        'snr',
        'spc',
        'spf',
        'sscs',
        'stppt',
        'svwu',
        'synt',
        'tdr',
        'tibc',
        'tpc',
        'tpco',
        'trnr',
        'twr',
        'ulaua',
        'unswu',
        'wil'
    )

    # DSC resources to export from this module
    # DscResourcesToExport = @()

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    # FileList = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData          = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags         = @(
                # General
                'Windows', 'WindowsServer', 'PowerShell', 'PSModule',
                'SysAdmin', 'Administration', 'Ops', 'WinOps', 'Utilities',
                'Monitoring', 'HealthCheck', 'Automation', 'Infrastructure',
                # Active Directory
                'ActiveDirectory', 'AD', 'RSAT', 'ADUser', 'ADComputer', 'ADGroup',
                'ADReplication', 'AccountManagement', 'Inventory', 'Audit', 'Compliance',
                # Network
                'Network', 'DNS', 'ARP', 'TCP', 'Ping', 'Subnet', 'CIDR', 'SSL',
                'NetStat', 'Traceroute', 'WinRM', 'Route', 'HostsFile', 'PublicIP',
                # System
                'CIM', 'Uptime', 'DiskSpace', 'PendingReboot', 'ScheduledTask',
                'InstalledSoftware', 'PageFile', 'EnvironmentVariable', 'Startup',
                # RDP / Sessions
                'RDP', 'RemoteDesktop', 'Sessions',
                # NTP / Time
                'NTP', 'TimeSynchronization', 'W32Time',
                # Proxy
                'Proxy', 'WinHTTP', 'WinINET',
                # Security / Utils
                'Security', 'Password', 'Encoding',
                # Server Roles / HealthCheck
                'DHCP', 'DFS', 'Cluster', 'HyperV',
                'IIS', 'PrintServer', 'WSUS', 'ADFS', 'Exchange', 'CertificateAuthority',
                'RDS', 'FileServer', 'DNSServer',
                # VSS / Shadow Copy
                'VSS', 'ShadowCopy', 'VolumeSnapshot', 'Backup', 'Restore'
            )

            # A URL to the license for this module.
            LicenseUri   = 'https://github.com/k9fr4n/PSWinOps/blob/main/LICENSE'

            # A URL to the main website for this project.
            ProjectUri   = 'https://github.com/k9fr4n/PSWinOps'

            # A URL to an icon representing this module.
            # IconUri = ''

            # ReleaseNotes of this module
            ReleaseNotes = '## 1.1.0 - 2026-09-05 UTC

### Added
- Short aliases for all 139 public functions (e.g. gwu for Get-WindowsUpdate, gaui for Get-ADUserInventory), registered via AliasesToExport.

## 1.0.0 - 2026-09-05 UTC
First stable release. Consolidates all work merged since 0.0.23 (2026-05-21),
none of which was previously published to the PowerShell Gallery.

### Added
- New eventlog domain: Get-UnexpectedShutdown, Get-LogonFailure, Get-ServiceCrashEvent, Get-ProcessCrashEvent, Get-DiskErrorEvent, Get-ScheduledTaskFailure, Get-WindowsUpdateFailure, Get-SchannelError
- New security domain: Get-AuditPolicy
- New certificate domain: Get-ExpiringCertificate
- Get-ADLockoutSource, Get-RebootHistory, Get-CrashDump, Get-DriverInventory
- Reset-NetworkStack, Get-ProcessByPort, Set-EnvironmentVariable, Stop-ProcessTree, Get-ServiceAccount
- Reset-WindowsUpdateComponent, ConvertTo-Markdown

### Changed
- Standardized action-function output on a typed PSWinOps.ActionResult shape (Clear-Arp, Edit-HostsFile, Remove-NetworkRoute, Set-NTPClient, Remove-ProxyConfiguration, Set-ProxyConfiguration, Clear-WindowsUpdateCache)
- Remove-UserProfile now reconciles registry profile entries against actual C:\Users folders

### Fixed
- Excluded Integration-tagged Pester tests from the Gallery publish workflow
- Added missing format views for Windows Update result types

See CHANGELOG.md for the full project history (0.0.1 - 1.0.0).'

            # Prerelease string of this module
            # Prerelease = ''

            # Flag to indicate whether the module requires explicit user acceptance for install/update/save
            # RequireLicenseAcceptance = $false


        } # End of PSData hashtable

    } # End of PrivateData hashtable

    # HelpInfo URI of this module
    # HelpInfoURI = ''

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''

}
